Listas não são legais para realização de cálculos. Eles são legais para se armazenar como uma estrutura de dados, e só. Para operações matemáticas, para utilizar uma "lista" como um vetor (ou matriz), será muito mais interessante e fácil utilizar o Numpy.

In [3]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height

[1.73, 1.68, 1.71, 1.89, 1.79]

In [6]:
weight = [85.4, 70.0, 64.6, 88.4, 68.7]
weight

[85.4, 70.0, 64.6, 88.4, 68.7]

In [8]:
imc = weight / height ** 2   # Aqui vai rolar um erro!!!!

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [9]:
import numpy as np

O ndarray é o array de n dimensões do numpy que fuciona como uma lista com possibilidade de se utilizar para realizar operações matemáticas.

Ele é:
* Um pacote de métodos numéricos do Python (numerical python)
* Uma alternativa às listas
* Os cálculos são realizados sobre todos os elementos do array
* É rápido e fácil, além de ser otimizado para data science

In [12]:
new_height = np.array(height)
new_weight = np.array(weight)

imc = new_weight / new_height ** 2
print(imc)

new_height.

[28.5341976  24.8015873  22.09226771 24.7473475  21.44127836]


```Python
Ndarray.all()
Ndarray.any()
Ndarray.argmax()
Ndarray.argmin()
Ndarray.argpartition()
Ndarray.argsort()
Ndarray.astype()
Ndarray.base()
Ndarray.byteswap()
Ndarray.choose()
Ndarray.clip()
Ndarray.compress()
Ndarray.conj()
Ndarray.conjugate()
Ndarray.copy()
Ndarray.cumprod()
Ndarray.cumsum()
Ndarray.diagonal()
Ndarray.dot()
Ndarray.dump()
Ndarray.dumps()
Ndarray.fill()
Ndarray.flags()
Ndarray.flat()
Ndarray.flatten()
Ndarray.getfield()
Ndarray.item()
Ndarray.itemset()
Ndarray.max()
Ndarray.mean()
Ndarray.min()
Ndarray.newbyteorder()
Ndarray.nonzero()
Ndarray.partition()
Ndarray.prod()
Ndarray.ptp()
Ndarray.put()
Ndarray.ravel()
Ndarray.repeat()
Ndarray.reshape()
Ndarray.resize()
Ndarray.round()
Ndarray.searchsorted()
Ndarray.setfield()
Ndarray.setflags()
Ndarray.sort()
Ndarray.squeeze()
Ndarray.std()
Ndarray.sum()
Ndarray.swapaxes()
Ndarray.take()
Ndarray.tobytes()
Ndarray.tofile()
Ndarray.trace()
Ndarray.transpose()
Ndarray.var()
Ndarray.view()
```

Vejamos uma diferença bem clara entre ambos. Se somarmos duas listas, elas serão concatenadas. Se somarmos dois ndarrays, cada elemento será somado.

In [14]:
la = [1, 2, 3, 4, 5]
lb = [6, 7, 8, 9, 1]

print(la+lb)
print(np.array(la) + np.array(lb))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1]
[ 7  9 11 13  6]


Outra coisa legal do ndarray é que ele permite que se obtenha um novo ndarray quando se faz uma verificação lógica.

In [19]:
valores_que_me_interessam = np.array(la) > 2
print(valores_que_me_interessam)

npla = np.array(la)

print(npla)
print(npla[npla>2])

[False False  True  True  True]
[1 2 3 4 5]
[3 4 5]


### N dimensões

Bom, até agora só vimos uma dimensão. Mas podemos ter infinitas delas. Para vermos quantas dimensões temos, e quantos elementos em cada dimensão temos, podemos utilizar o dnarray.shape().

In [20]:
print(type(npla))

<class 'numpy.ndarray'>


In [29]:
np_2d = np.array([la, lb])
print(np_2d.shape) # Temos 2 linhas e 5 colunas.

(2, 5)


### Selecionar elementos em arrays de mais de uma dimensão

In [31]:
print(np_2d)

[[1 2 3 4 5]
 [6 7 8 9 1]]


In [33]:
x = np_2d[0][1]
y = np_2d[0,1]
print(x, y)


help(np.column_stack)


2 2
Help on function column_stack in module numpy:

column_stack(tup)
    Stack 1-D arrays as columns into a 2-D array.
    
    Take a sequence of 1-D arrays and stack them as columns
    to make a single 2-D array. 2-D arrays are stacked as-is,
    just like with `hstack`.  1-D arrays are turned into 2-D columns
    first.
    
    Parameters
    ----------
    tup : sequence of 1-D or 2-D arrays.
        Arrays to stack. All of them must have the same first dimension.
    
    Returns
    -------
    stacked : 2-D array
        The array formed by stacking the given arrays.
    
    See Also
    --------
    stack, hstack, vstack, concatenate
    
    Examples
    --------
    >>> a = np.array((1,2,3))
    >>> b = np.array((2,3,4))
    >>> np.column_stack((a,b))
    array([[1, 2],
           [2, 3],
           [3, 4]])

