fdsafds

In [1]:
import tensorflow as tf

2023-11-03 15:49:40.109696: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
d0 = tf.ones((1,))
d1 = tf.ones((2, ))
d2 = tf.ones((2, 2))
d3 = tf.ones((2, 2, 2))

In [13]:
print("Scalar:\n", d0.numpy())
print("1 dimension:\n", d1.numpy())
print("2 dimension:\n", d2.numpy())
print("3 dimension:\n", d3.numpy())

Scalar:
 [1.]
1 dimension:
 [1. 1.]
2 dimension:
 [[1. 1.]
 [1. 1.]]
3 dimension:
 [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [6]:
d2.numpy()

array([[1., 1.],
       [1., 1.]], dtype=float32)

### Using convenience functions to define constants

In [15]:
print(tf.constant([1, 2, 3]))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [16]:
print(tf.zeros([2,2]))

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [17]:
print(tf.zeros_like(d3))

tf.Tensor(
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]], shape=(2, 2, 2), dtype=float32)


In [18]:
print(tf.ones([2,2]))

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [20]:
print(tf.ones_like(d3))

tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)


In [21]:
print(tf.fill([3,3], 7))

tf.Tensor(
[[7 7 7]
 [7 7 7]
 [7 7 7]], shape=(3, 3), dtype=int32)


### Defining and initializing variables

In [22]:
a0 = tf.Variable([1, 2, 3, 4, 5, 6], dtype = tf.float32)
a1 = tf.Variable([1, 2, 3, 4, 5, 6], dtype = tf.int16)

In [23]:
a0.numpy()

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [24]:
a1.numpy()

array([1, 2, 3, 4, 5, 6], dtype=int16)